// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWxrZtq6edcSlPYVB0GSEx1gwCGJdkeU',
    appId: '1:614717346303:web:5d79d60244c47fc40357ca',
    messagingSenderId: '614717346303',
    projectId: 'rutaiq-9741d',
    authDomain: 'rutaiq-9741d.firebaseapp.com',
    storageBucket: 'rutaiq-9741d.firebasestorage.app',
    measurementId: 'G-L2JEWPC7N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNNDDHxJM1kY8-0NBaA1F876jKXjojR0',
    appId: '1:614717346303:android:678607f92d3141390357ca',
    messagingSenderId: '614717346303',
    projectId: 'rutaiq-9741d',
    storageBucket: 'rutaiq-9741d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0I-PqCNtH9MW6UXgeowmzc12pBIaZ-P0',
    appId: '1:614717346303:ios:5ef7be3d0fee47d90357ca',
    messagingSenderId: '614717346303',
    projectId: 'rutaiq-9741d',
    storageBucket: 'rutaiq-9741d.firebasestorage.app',
    androidClientId: '614717346303-68bcfe4mcjsdcqb21a9te42u6df9cchm.apps.googleusercontent.com',
    iosClientId: '614717346303-o38deqo9o2c9vd261ub27r13hda9a99o.apps.googleusercontent.com',
    iosBundleId: 'com.rutaiq.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0I-PqCNtH9MW6UXgeowmzc12pBIaZ-P0',
    appId: '1:614717346303:ios:5ef7be3d0fee47d90357ca',
    messagingSenderId: '614717346303',
    projectId: 'rutaiq-9741d',
    storageBucket: 'rutaiq-9741d.firebasestorage.app',
    androidClientId: '614717346303-68bcfe4mcjsdcqb21a9te42u6df9cchm.apps.googleusercontent.com',
    iosClientId: '614717346303-o38deqo9o2c9vd261ub27r13hda9a99o.apps.googleusercontent.com',
    iosBundleId: 'com.rutaiq.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUWxrZtq6edcSlPYVB0GSEx1gwCGJdkeU',
    appId: '1:614717346303:web:ed14b2536f6b72b70357ca',
    messagingSenderId: '614717346303',
    projectId: 'rutaiq-9741d',
    authDomain: 'rutaiq-9741d.firebaseapp.com',
    storageBucket: 'rutaiq-9741d.firebasestorage.app',
    measurementId: 'G-4PZPGG9HB5',
  );
}
